server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/words_learning_backend
    username: postgres
    password: postgres
  liquibase:
    url: jdbc:postgresql://localhost:5432/words_learning_backend
    user: postgres
    password: postgres
    liquibase-schema: liquibase
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/words-learning
logging:
  level:
    org:
      springframework:
        security: DEBUG